### ISSUE TITLE
QGIS is crashing when trying to load area styles

### ISSUE THREAD

**Issue by mtravis** [OrdnanceSurvey/OS-VectorMap-Local-stylesheets#1]
When I try and load the styles for area (from both backdrop and full colour) QGIS crashes.

I'm using 2.2 and can load all the other styles fine (they look great btw). The data I'm using is in GML format. 

Thanks

Matt

**Comment by ghost** [comment]
Hi Matt,

Sorry to here that.
The usual cause for this is when the SVG folder hasn't been installed correctly.
Make sure you copy the folder called 'ordnance_survey' such that you have a filepath (in Windows) of 'C:\Program Files\QGIS Valmiera\apps\qgis\svg\ordnance_survey'.

You may need to reboot your computer. Do this, and install the font, before trying to load in any of the QML.

SVG is a bit troublesome at the moment but the appearance is so much better than using a font for the vegetation patterns.

Regards,

Chris

**Comment by charleyglynn** [comment]
@mtravis - Are you still getting this issue in newer versions of QGIS?

**Comment by mtravis** [comment]
Not had chance to try it yet. I'll give it a go in 2.6 soon and let you
know.

**Comment by charleyglynn** [comment]
Hey @mtravis - Do you still get this issue in 2.6 and/or 2.8? I'm working on some new stylesheets and 2.6.1 keeps crashing when I use more than a few SVG fills

**Comment by mtravis** [comment]
Hi @charleyglynn 

I still haven't got around to testing this out in 2.6 / 2.8. 

Will try and get around to it at some point.

**Comment by charleyglynn** [comment]
No worries, cheers Matt - Chris and I have run some tests and all seems to be working fine now in 2.6 and 2.8
