### ISSUE TITLE
Cannot update orientation in ArcGIS Pro 2.3 as per guide

### ISSUE THREAD

**Issue by Chaz6** [OrdnanceSurvey/OS-VectorMap-Local-stylesheets#11]
The guide at https://github.com/OrdnanceSurvey/OS-VectorMap-Local-stylesheets/tree/master/Geopackage%20stylesheets/ESRI%20Stylesheets%20(LYR)/Full%20Colour%20style says that the orientation must be updated, but when using ArcGIS Pro, it fails with the following output:-

```
ERROR 999999: Something unexpected caused the tool to fail. Contact Esri Technical Support (http://esriurl.com/support) to Report a Bug, and refer to the error help for potential solutions or workarounds.
 The operation is not supported by this implementation.
 The operation is not supported by this implementation.
 The operation is not supported by this implementation.
 The operation is not supported by this implementation.
 The operation is not supported by this implementation.
 The operation is not supported by this implementation.
 Failed to execute (CalculateField).
```

I suspect this is an ArcGIS bug but I have raised an issue here for information.

**Comment by egil1978** [comment]
Thanks for the information. Our stylesheets are built for ArcMap and we are aware that some of the styling does not transfer across so easily to Pro.
