### ISSUE TITLE
spelling mistake in VML RoadCentreLines SLD

### ISSUE THREAD

**Issue by mixedbredie** [OrdnanceSurvey/OS-VectorMap-Local-stylesheets#2]
In the road centre lines SLD the vendor options for the road labels contain a spelling mistake.
VendorOption name="**forceLeftToRigth**"
should be
VendorOption name="**forceLeftToRight**"

See http://docs.geoserver.org/latest/en/user/_sources/styling/sld-reference/labeling.txt

**Comment by charleyglynn** [comment]
Cheers @mixedbredie - now corrected
