### ISSUE TITLE
QML styles use incorrect field names

### ISSUE THREAD

**Issue by ghost** [OrdnanceSurvey/OS-VectorMap-Local-stylesheets#5]
Current QML files refer to the following field names:
+ `featureCod` - should be `FeatCode`
+ `featureDes` - should be `FeatDesc`

![qml-field-names](https://user-images.githubusercontent.com/19981049/40649628-50fa0cd2-6329-11e8-9149-88f3757e0f88.JPG)

**Comment by charleyglynn** [comment]
This will differ between the GML and SHP - we have stylesheets for both.
Cheers
Charley
