### ISSUE TITLE
OS vml - Area font

### ISSUE THREAD

**Issue by Shohreh-Hosseini** [OrdnanceSurvey/OS-VectorMap-Local-stylesheets#6]
I loaded the gml style to the area but the green areas show question marks. How can I solve this issue?

Thanks

**Comment by charleyglynn** [comment]
You need to ensure that you have the font and SVGs installed. There is more detail in the README.
Hope that helps, let me know how you get on.
Charley

**Comment by Shohreh-Hosseini** [comment]
Hi Charley,

Thanks for your reply. Unfortunately, I couldn't find the font. Could you please let me know which font needs to be installed and where I can download it from?

Regards
Shohreh

**Comment by Shohreh-Hosseini** [comment]
Hi Charley,

I installed the OS_VMLocal font into my windows font directory but still I get questions marks on my maps as you can see in the below picture.
![002](https://user-images.githubusercontent.com/26904170/45690507-65872900-bb4e-11e8-9246-da8d123a786c.png)

Looking forward to hearing from you.

Kind reagards,

Shohreh

**Comment by charleyglynn** [comment]
Hi Shoreh, the font will take care of some symbols but did you also install the folder of SVGs into the relevant QGIS folder? 

These SVGs: https://github.com/OrdnanceSurvey/OS-VectorMap-Local-stylesheets/tree/master/GML%20stylesheets/QGIS%20stylesheets%20(QML)/Full%20Colour%20style/ordnance_survey

**Comment by Shohreh-Hosseini** [comment]
Hi Charley,

I still have problem with os-vml file. It doesn't read the font and shows question marks. I download the QML file again and replaced it with the old files in SVGs folder into the relevant QGIS folder and font is installed in windows.
I did the same thing for the os_vmd file and it is absolutely fine . Noe, I am confused what am I missing here?!
