### ISSUE TITLE
Invalid SLDs

### ISSUE THREAD

**Issue by mpdaly** [OrdnanceSurvey/OS-VectorMap-Local-stylesheets#7]
The RoadCLine SLDs, both Backdrop _and_ Full Colour, have invalid XML wherever "strConcat" is used, eg:

https://github.com/OrdnanceSurvey/OS-VectorMap-Local-stylesheets/blob/f7fb09cfc3cef334ce75390936d23e067073222a/GML%20stylesheets/GeoServer%20stylesheets%20(SLD)/Backdrop%20style/VML-backdrop-RoadCLine.sld#L2651-L2655

Note the extra `</ogc:Function>` tag between the `<ogc:PropertyName>` and `<ogc:Literal>` being concatenated. There are four occurrences in each file.

**Comment by egil1978** [comment]
Hi, thanks for spotting. These 4 instances of the </ogc:Function> tag have now been removed from the backdrop and full colour SLD
