### ISSUE TITLE
RoadCLine Text Halos In SLDs

### ISSUE THREAD

**Issue by mpdaly** [OrdnanceSurvey/OS-VectorMap-Local-stylesheets#9]
Several halos seem large wrt to the font size, eg 7m halo on 10m text:

https://github.com/OrdnanceSurvey/OS-VectorMap-Local-stylesheets/blob/af1b64189b01c10c061cd1af49c5ac0710f96407/GML%20stylesheets/GeoServer%20stylesheets%20(SLD)/Full%20Colour%20style/VML-fullcolour-RoadCLine.sld#L2829-L2864

Are these the correct values?

**Comment by egil1978** [comment]
Good spot, road label halo's have been reduced to 1.5 for text that is 12 and to 3 for text that is 20.
